name: XAntiRelog
version: ${project.version}
main: me.xentany.antirelog.AntiRelogPlugin
api-version: 1.16
softdepend:
  - Essentials
  - SuperVanish
  - PremiumVanish
  - VanishNoPacket
  - WorldGuard
  - LibsDisguises
  - CMI
  - ProtocolLib
authors:
  - x3ntany
  - Leymooo
commands:
  xantirelog: {}